hydra:
  run:
    dir: hydra_output/


data:
  exp_name: test
  data_dir: ./input
  seed: 0
  img_size: &image_size 224
  n_splits: 5
  cv: stratifiedgroup
  checkpoint_path: ./checkpoints

train:
  mode: None
  lr: 1e-4
  epoch: 160
  fold: 0
  only_one_fold: True
  batch_size: 16
  num_workers: 8
  weight_decay: 1e-5
  backbone: resnet34d
  tta_num: 4
  optimizer: adam
  mixup_alpha: 0
  mixup_pct: 0.5
  cutmix_alpha: 0
  cutmix_pct: 0.5

aug_kwargs:
  train:
    Resize: {"height": *image_size, "width": *image_size}
    ToGray: { "p": 0.2 }
    HorizontalFlip: { "p": 0.5 }
    VerticalFlip: { "p": 0.5 }
    RandomRotate90: { "p": 0.5 }
    Normalize: {"mean": [0.485, 0.456, 0.406], "std": [0.229, 0.224, 0.225], "p": 1.0}
    CoarseDropout: {"max_holes": 8, "max_width": 8, "max_height": 8}

  val:
    Resize: {"height": *image_size, "width": *image_size}
    Normalize: {"mean": [0.485, 0.456, 0.406], "std": [0.229, 0.224, 0.225]}

  test:
    Resize: {"height": *image_size, "width": *image_size}
    HorizontalFlip: { "p": 0.5 }
    VerticalFlip: { "p": 0.5 }
    Normalize: {"mean": [0.485, 0.456, 0.406], "std": [0.229, 0.224, 0.225]}