version: '3'
services:
  env:
    build: ./
    container_name: atma_env
    user: root
    shm_size: 24gb
    # Use GPU
    # ref: https://qiita.com/gonzou122/items/7b5e74d7c4c5f3e969af
    deploy:
      resources:
        limits:
          cpus: "12"
        reservations:
          devices:
            - 'driver': 'nvidia'
              'capabilities': [ 'gpu' ]
    volumes:
      - ./:/workspace
    working_dir: /workspace
    tty: true
    command: bash